### ISSUE TITLE
Update URL # on change?

### ISSUE THREAD

**Issue by vilbht** [maliMirkec/Classily.js#1]
Hi 

Is there a way to use the URL to drive the action of changing classes?

So for instance _xyz.com?color=green_ can show the element with the class changed so a text element appears in green, for example?

**Comment by maliMirkec** [comment]
Hi!

Thank you for opening the ticket.

I'm not sure if I understand this request:
Do you want to change the class of an element on URL change?
For example, if I land on _xyz.com?color=green, the element should have green text?

**Comment by vilbht** [comment]
yup, that's what I meant. I was hoping to do this through classify because i want the user to be able to swap a class if they don't find the URL-based class switching acceptable..

**Comment by maliMirkec** [comment]
That could be very hard to implement, IMO. 

Here's what bothers me:
- How to target an element?
- How to target multiple elements?

One solution comes to my mind: _xyz.com?classily-target=.selector1,.selector2&classily-class=class1,class2_.

I don't think that will be maintainable and that looks like a real mess. 

Can you imagine how this would look if we have more Classily triggers?

**Comment by maliMirkec** [comment]
Closed and abandoned.
